### ISSUE TITLE
README.md missing

### ISSUE THREAD

**Issue by weihua916** [emforce77/rwlspegate2#1]
Hi! thank you for submitting to OGB-LSC leaderboards. Could you please add README.md to give instructions on reproducing your performance? Good example is [this](https://github.com/PaddlePaddle/PaddleHelix/tree/dev/apps/pretrained_compound/ChemRL/GEM-2)

OGB-LSC team

**Comment by emforce77** [comment]
Thank you for telling me about the correction. 
I am very sorry for my insufficient submission. 
I would appreciate it if you could let me know whenever you need to supplement anything.


https://github.com/emforce77/rwlspegate2




-----Original Message-----
From: "Weihua ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2023-02-22 (수) 08:48:24 (GMT+09:00)
Subject: [emforce77/rwlspegate2] README.md missing (Issue #1)

Hi! thank you for submitting to OGB-LSC leaderboards. Could you please add README.md to give instructions on reproducing your performance? Good example is this

**Comment by emforce77** [comment]
I am sending you the mail again because you haven't read it yet.

Thank you for telling me about the correction. 
I am very sorry for my insufficient submission. 
I would appreciate it if you could let me know whenever you need to supplement anything.


https://github.com/emforce77/rwlspegate2




-----Original Message-----
From: "Weihua ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2023-02-22 (수) 08:48:24 (GMT+09:00)
Subject: [emforce77/rwlspegate2] README.md missing (Issue #1)

Hi! thank you for submitting to OGB-LSC leaderboards. Could you please add README.md to give instructions on reproducing your performance? Good example is this

**Comment by emforce77** [comment]
> Hi! thank you for submitting to OGB-LSC leaderboards. Could you please add README.md to give instructions on reproducing your performance? Good example is [this](https://github.com/PaddlePaddle/PaddleHelix/tree/dev/apps/pretrained_compound/ChemRL/GEM-2)
> 
> OGB-LSC team

**Comment by weihua916** [comment]
Thanks! We've updated the leaderboard to include your entry :)
https://ogb.stanford.edu/docs/lsc/leaderboards/
